FROM java:8 

# Install maven
RUN apt-get update
RUN apt-get install -y maven

WORKDIR /sivaraja

# Prepare by downloading dependencies
ADD pom.xml /sivaraja/pom.xml
RUN ["mvn", "dependency:resolve"]
#RUN ["mvn", "verify"]

# Adding source, compile and package into a fat jar
ADD src /sivaraja/src
RUN ["mvn", "clean", "package"]

RUN bash -c 'ls -la /sivaraja/target/'

RUN bash -c 'ls -la /sivaraja/target/course-api-data-0.0.1-SNAPSHOT.jar'

EXPOSE 8181

#CMD ["/usr/lib/jvm/java-8-openjdk-amd64/bin/java", "-jar", "/sivaraja/target/course-api-data-0.0.1-SNAPSHOT.jar"]
ENV JAVA_OPTS="-cp"
#ENTRYPOINT exec /usr/lib/jvm/java-8-openjdk-amd64/bin/java -cp /sivaraja/target/course-api-data-0.0.1-SNAPSHOT.jar org.aathis.springboot.CourseApiApp

ENTRYPOINT exec /usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar /sivaraja/target/course-api-data-0.0.1-SNAPSHOT.jar 